spring.application.name=library

spring.datasource.url=jdbc:postgresql://localhost:5432/mylibrary
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.private.key=classpath:certs/private.pem
jwt.public.key=classpath:certs/public.pem

frontend.url=http://localhost:5173

app.seed.admin-password=${SEED_ADMIN_PASSWORD}
app.seed.user-password=${SEED_USER_PASSWORD}